inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-packaging
  - rubocop-rspec


AllCops:
  TargetRubyVersion: 3.1
  EnabledByDefault: true
  NewCops: enable
  UseCache: true
  Exclude:
    - '**/.git/**/*'
    - '**/tmp/**/*'
    - '**/vendor/**/*'
  CacheRootDirectory: tmp
  MaxFilesInCache: 36000

Packaging/RequireHardcodingLib:
  Enabled: false

Packaging/RequireRelativeHardcodingLib:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Metrics/CyclomaticComplexity:
  Severity: info

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Severity: info

Naming/MethodParameterName:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Severity: info

Gemspec/DependencyVersion:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Lint/NumberConversion:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Severity: info

Metrics/ParameterLists:
  Enabled: false

Style/GuardClause:
  Enabled: false

Metrics/BlockNesting:
  Severity: info

RSpec/MultipleExpectations:
  Enabled: false

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Lint/ConstantResolution:
  Enabled: false

